# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Use three inputs to generate random walk metropolis samples using Rcpp.
#' @description Use normal and uniform distribution to do this job
#' @param sigma the first predictor (numeirc)
#' @param a the second predictor (numeric)
#' @param N the third predictor (numeric)
#' @return a random sample of size \code{N}
#' @examples
#' \dontrun{
#' rw <- rwMetropolisC(2,25,1000)
#' }
#' @export
rwMetropolisC <- function(sigma, a, N) {
    .Call('_SC19020_rwMetropolisC', PACKAGE = 'SC19020', sigma, a, N)
}

